# =============================================
# Configuracion de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios_hex
db.username=root
db.password=

# =============================================
# Configuracion SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=gabrielaorozco035@gmail.com
smtp.password=hlmx oekp sncx eufq
smtp.from.address=gabrielaorozco0353@gmail.com
smtp.from.name=Gestion de Usuarios

